import React from 'react'
import Dialog from '@mui/material/Dialog';
import { Box, Typography } from '@mui/material';
import Input from '@mui/joy/Input';
import CloseIcon from '@mui/icons-material/Close';
import Button from '@mui/joy/Button';

export default function CommentPage({ data, setcomment, comment }) {
    console.log(comment)
    return (
        <Dialog PaperProps={{ sx: { width: '150vh', maxWidth: '150vh' } }} open={comment}>
            <Box sx={{ display: 'flex' }}>
                <Box sx={{ flex: 2.5, padding: '10px' }}> <img style={{ width: '100%', borderRadius: '10px', height: '100%' }} src={data.photo} alt="" srcset="" /> </Box>
                <Box sx={{ background: 'green', flex: 2, padding: "10px" }}>
                    <Box sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between', height: '100%',width:'100%' }}>

                        <Box sx={{ display: 'flex', justifyContent: 'space-between', paddingBottom: 1, alignItems: 'center', borderBottom: '1px solid red' }}>
                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>

                                <img src={data.profilePic} style={{ height: '2.5rem', width: '2.5rem', borderRadius: '50%' }} alt="owner Pic" srcset="" />
                                <Typography>{data.username}</Typography>
                            </Box>
                            <CloseIcon onClick={() => setcomment(false)} sx={{ cursor: 'pointer' }} />
                        </Box>
                        <Box>dasasdas
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                            das
                        </Box>
                        <Box sx={{ display: 'flex',gap:2,alignItems:'center'}}>
                            <Box sx={{flex:6}}><Input sx={{ width:"100%" }} placeholder="Add Comment..." variant="solid" /></Box>
                            <Box sx={{flex:1}}>

                            <Button>Button</Button>
                            </Box>

                        </Box>

                    </Box>

                </Box>
            </Box>
        </Dialog>
    )
}
